- name: Enable syncookies
  become: yes
  shell: sysctl -w net/ipv4/tcp_syncookies=1

- name: Ignore ICMP echo broadcasts
  become: yes
  shell: sysctl -w net/ipv4/icmp_echo_ignore_broadcasts=1

- import_tasks: iptables.yml