- name: Add Brave key to apt
  become: yes
  shell: curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

- name: Add Brave repository to sources
  become: yes
  shell: echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

- name: Update
  become: yes
  apt:
      update_cache: true

- name: Install Brave
  become: yes 
  apt:
      pkg:
      - brave-browser