- git_config:
    name: alias.ci
    scope: global
    value: commit

- git_config:
    name: alias.st
    scope: global
    value: status

- git_config:
    name: alias.co
    scope: global
    value: checkout