- name: Update
  become: yes
  apt:
      update_cache: true
- name: Upgrade
  become: yes
  apt:
      upgrade: full
- name: Install packages
  become: yes 
  apt:
      pkg:
      - vim
      - wget
      - curl
      - wireshark

- import_tasks: vim.yml
