- name: Update
  become: yes
  apt:
      update_cache: true
- name: Upgrade
  become: yes
  apt:
      upgrade: full
- name: Install packages
  become: yes 
  apt:
      pkg:
      - vim
      - wget
      - curl
      - zsh
      - wireshark

- name: Change default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- import_tasks: vim.yml
- import_tasks: zsh.yml
- import_tasks: vscode.yml
